name: AI-Mirror
on:
  schedule: [ { cron: "*/15 * * * *" } ]
  workflow_dispatch: {}
permissions: { contents: write, actions: write, issues: write }
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm install js-yaml
      - run: node scripts/ai_mirror_analyzer.js
      - run: node scripts/ai_optimizer.js
      - run: node scripts/ai_predictor.js
      - env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
        run: |
          git config user.name "auto-mirror-bot"; git config user.email "auto-mirror@users.noreply.github.com"
          git add .github/workflows/*.yml status/*.json || true
          git commit -m "AI-Mirror: Auto optimization cycle" || echo "No changes"
          git push origin HEAD:mirror-auto || true
          gh pr create --title "AI-Mirror Optimization" --body "Automated improvements from AI-Mirror layer." || true
      - uses: actions/github-script@v7
        with:
          script: |
            const num = parseInt(process.env.HEARTBEAT_ISSUE_NUMBER||0,10)||null;
            if(!num) return;
            await github.rest.issues.createComment({ owner: context.repo.owner, repo: context.repo.repo, issue_number: num, body: '🪞 AI-Mirror: Optimization cycle completed.' });
