name: Recovery
on:
  workflow_run: { workflows: ["Heartbeat"], types: [completed] }
  workflow_dispatch:
permissions: { contents: write, issues: write }
jobs:
  heal:
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: node scripts/patch_gas.js
      - run: |
          git config user.name "auto-heal-bot"; git config user.email "auto-heal@users.noreply.github.com"
          git add -A; git commit -m "auto: patch GAS (self-heal)" || echo "no changes"
      - uses: benc-uk/workflow-dispatch@v1
        with: { workflow: gas-deploy.yml }
      - uses: actions/github-script@v7
        with:
          script: |
            const num = parseInt(process.env.HEARTBEAT_ISSUE_NUMBER||0,10)||null;
            if(!num) return;
            await github.rest.issues.createComment({ owner: context.repo.owner, repo: context.repo.repo, issue_number: num, body: 'Recovery attempted: patched GAS and re-deployed.' });
