name: Secrets Audit

on:
  schedule:
    # Daily at 03:00 UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Verify required secrets
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
          SCRIPT_ID: ${{ secrets.SCRIPT_ID }}
          DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }}
          WEB_APP_URL: ${{ secrets.WEB_APP_URL }}
        run: |
          echo "Auditing required secrets..."

          missing=()

          if [ -z "$CLASPRC_JSON" ]; then
            missing+=("CLASPRC_JSON")
          fi

          if [ -z "$SCRIPT_ID" ]; then
            missing+=("SCRIPT_ID")
          fi

          if [ -z "$DEPLOYMENT_ID" ]; then
            missing+=("DEPLOYMENT_ID")
          fi

          if [ -z "$WEB_APP_URL" ]; then
            missing+=("WEB_APP_URL")
          fi

          if [ ${#missing[@]} -gt 0 ]; then
            echo "❌ Missing required secrets:"
            for secret in "${missing[@]}"; do
              echo "  - $secret"
            done
            exit 1
          fi

          echo "✔ All required secrets are present"
          echo "  - CLASPRC_JSON: ${#CLASPRC_JSON} bytes"
          echo "  - SCRIPT_ID: ${#SCRIPT_ID} chars"
          echo "  - DEPLOYMENT_ID: ${#DEPLOYMENT_ID} chars"
          echo "  - WEB_APP_URL: ${#WEB_APP_URL} chars"
