name: Update via Issue

on:
  issues:
    types: [opened, edited]

jobs:
  apply:
    if: contains(github.event.issue.title, 'Update PWA')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Parse issue body into files
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Parse PWA update"
          content-filepath: .github/ISSUE_TEMPLATE/temp.md

      - name: Apply update
        run: |
          echo "Writing files from issue body..."
          echo "${{ github.event.issue.body }}" > issue-body.txt
          npx @vercel/issue-parser issue-body.txt

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -B gh-pages
          git add -A
          git commit -m "Update from Issue #${{ github.event.issue.number }}" || echo "No changes to commit"
          git push origin gh-pages
